### ISSUE TITLE
Android: IndexSizeError when deleting characters on end of block

### ISSUE THREAD

**Issue by hannesstruss** [the-grid/ed#29]
Console output: 

```
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 23 is larger than or equal to the node's length (22).
```

`23` changes depending on where the caret is while typing

**Comment by bergie** [comment]
This ends up "escaping" selections, and weird jumping-around of the cursor.

**Comment by hannesstruss** [comment]
Actually this one only happens when deleting characters at the end of a block. Updated the title.

**Comment by hannesstruss** [comment]
Also sometimes after typing the caret stays in the middle of a word and things get a bit messed (see end of gif):

![mvx37mn52h](https://cloud.githubusercontent.com/assets/115381/12514719/fae24420-c124-11e5-9c89-284fd10e74c3.gif)

**Comment by bergie** [comment]
Initial suspect:

``` javascript
src/menu/context-menu.js:  let rects = window.getSelection().getRangeAt(0).getClientRects()
```

But could also be in upstream ProseMirror.

http://stackoverflow.com/questions/22935320/uncaught-indexsizeerror-failed-to-execute-getrangeat-on-selection-0-is-not
http://stackoverflow.com/questions/29831188/erro-when-try-use-setstart-and-setend-on-range-uncaught-indexsizeerror-failed

**Comment by hannesstruss** [comment]
Got the source maps to run, it's `selection.js:153`

**Comment by hannesstruss** [comment]
Stacktrace:

```
Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 44 is larger than or equal to the node's length (43).t.SelectionState.j.value @ selection.js:153t.SelectionState.j.value @ selection.js:116t.SelectionState.j.value @ selection.js:109t.SelectionState.j.value @ selection.js:176t.ProseMirror.s.value @ main.js:247t.ProseMirror.s.value @ main.js:243t.ProseMirror.s.get @ main.js:98i @ domchange.js:24a @ domchange.js:50b.input @ input.js:291(anonymous function) @ input.js:42
selection.js:153 Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 43 is larger than or equal to the node's length (42).t.SelectionState.j.value @ selection.js:153t.SelectionState.j.value @ selection.js:116t.SelectionState.j.value @ selection.js:109t.SelectionState.j.value @ selection.js:176t.ProseMirror.s.value @ main.js:247t.ProseMirror.s.value @ main.js:243t.ProseMirror.s.get @ main.js:98i @ domchange.js:24a @ domchange.js:50b.input @ input.js:291(anonymous function) @ input.js:42
```

**Comment by bergie** [comment]
Source code: https://github.com/ProseMirror/prosemirror/blob/master/src/edit/selection.js#L153

**Comment by hannesstruss** [comment]
Can't reproduce it anymore :(

**Comment by bergie** [comment]
However, seeing the same behavior with both Chrome on Android and Safari on iOS with http://prosemirror.net/demo/basic.html -- when making a selection, the selection dismisses immediately

**Comment by forresto** [comment]
re: https://github.com/ProseMirror/prosemirror/issues/145

**Comment by forresto** [comment]
pm #145 is fixed, but holding delete also hits https://github.com/ProseMirror/prosemirror/issues/218

**Comment by hannesstruss** [comment]
The autocorrect breakage also still exists in PM, when used in a webview. Chrome/Android works a lot better. https://github.com/ProseMirror/prosemirror/issues/149

**Comment by forresto** [comment]
@hannesstruss fixed with Ed 0.7.1?

**Comment by forresto** [comment]
@hannesstruss Doesn't look like it :disappointed:
